name: math_expressions_builder
description: A stable Dart package to programmatically build and manipulate LaTeX math expressions using a tree-based structure.
<<<<<<< HEAD
version: 1.0.4
=======
version: 1.0.2
>>>>>>> 47e6959bd980efbd79f3a08fcc270e570519968f
repository: https://github.com/Ashraf-Hamdoun/Math-Expressions-Builder.git
homepage: https://github.com/Ashraf-Hamdoun/Math-Expressions-Builder
issue_tracker: https://github.com/Ashraf-Hamdoun/Math-Expressions-Builder/issues

environment:
  sdk: '>=3.8.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0