name: math_latex_builder
description: A Dart package to programmatically build and manipulate LaTeX math expressions using a tree-based structure.
version: 1.0.6
repository: https://github.com/your_username/math_latex_builder
homepage: https://github.com/your_username/math_latex_builder
issue_tracker: https://github.com/your_username/math_latex_builder/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
