name: math_latex_builder
description: A Dart package to programmatically build and manipulate LaTeX math expressions using a tree-based structure.
version: 1.0.11
repository: https://github.com/Ashraf-Hamdoun/Math-LaTeX-Builder.git
homepage: https://github.com/Ashraf-Hamdoun/Math-LaTeX-Builder
issue_tracker: https://github.com/Ashraf-Hamdoun/Math-LaTeX-Builder/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
