


name: math_expressions_builder
description: A stable Dart package to programmatically build and manipulate LaTeX math expressions using a tree-based structure.
version: 1.0.0
repository: https://github.com/Ashraf-Hamdoun/math_expressions_builder.git
homepage: https://github.com/Ashraf-Hamdoun/math_expressions_builder
issue_tracker: https://github.com/Ashraf-Hamdoun/math_expressions_builder/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0